apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-static-site
  labels:
    app: saas-static-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas-static-site
  template:
    metadata:
      labels:
        app: saas-static-site
    spec:
      containers:
        - name: saas-static-site
          image: registry.digitalocean.com/shagun-do-prep/saas-static-site   
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
